challenges/web/web3-cs6443/ssrf/app/flaskr/basic_bp/models.py
from flask import current_app
from ..app import db
import secrets

class User(db.Model):
    __tablename__ = "appuser"
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.Text(), index=True)
    password = db.Column(db.Text(), index=True)
    profile_picture_data = db.Column(db.LargeBinary)

def populate():
    if User.query.filter_by(id=1).first():
        return

    user = User(username="admin", password=current_app.config.get("ADMIN_PASSWORD"))
    db.session.add(user)
    db.session.commit()

challenges/web/web3-cs6443/ssrf/app/flaskr/models.py
from flaskr.basic_bp import models

challenges/web/web3-cs6443/ssrf/app/flaskr/__init__.py
from flaskr.app import (
    create_app, db
)

challenges/web/web3-cs6443/ssrf/app/flaskr/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import logging
import os

db = SQLAlchemy()

def get_current_ip():
    with open("/etc/hosts") as f:
        lines = f.readlines()
    return lines[-1].split('\t')[0]


class ConfigClass(object):
    # Flask settings
    # DEBUG = True
    SECRET_KEY                      = 'fuckyouandyoursecretkey'
    SQLALCHEMY_DATABASE_URI         = 'postgresql+psycopg2://adminisbestusername:hunter2isbestpassword@db:5432/magicdatabase'
    #SQLALCHEMY_DATABASE_URI         = 'sqlite:////tmp/tmp.sqlite'
    SQLALCHEMY_ECHO                 = True
    FLAG1 = os.getenv("FLAG", "flag{this_isnt_a_flag_but_youre_making_progress}")
    SSRF_HOST = os.getenv("SSRF_HOST", "ssrf")
    SECRET_KEY = "awerglllaliwuhgoiaweuhto8q237598oq27y3toiuq23hteoiuawh"
    ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "FLAG{jdusNrj8Fm8jnW84zcWZS9IJUqp7X2OgFIaZMrVID2ArAXXvp_EgLlE4RXu38mIogMijb_3gwAY}")

    THIS_IP = get_current_ip()

def register_models(app):
    from .basic_bp import models

    with app.app_context():
        db.init_app(app)
    #    db.drop_all()
        db.create_all()

        models.populate()

def register_blueprints(app):
    from .basic_bp import app as basic_bp
    app.register_blueprint(basic_bp)

def create_app():
    app = Flask(__name__)
    app.config.from_object(__name__ + '.ConfigClass')

    register_models(app)
    register_blueprints(app)

    return app

challenges/web/web3-cs6443/ssrf/app/flaskr/basic_bp/__init__.py
from flask import Blueprint

app = Blueprint('app',
    __name__,
    template_folder='templates',
    static_folder='static')

from . import views

challenges/web/web3-cs6443/ssrf/app/flaskr/basic_bp/views.py
from flask import render_template, request, redirect, current_app, Flask, flash, url_for, Response, session
from . import app
import urllib.parse
import socket
import requests
import base64

from .models import User
from flaskr import db

def get_hostname(full_url):
    url = urllib.parse.urlparse(full_url)
    hostname = url.netloc.split(":")[0]
    return hostname

@app.after_request
def per_request_callbacks(response):
    response.headers['X-Server'] = current_app.config.get("THIS_IP").strip()
    response.headers['FLAG'] = current_app.config.get("FLAG1").strip()
    return response

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method=='POST':
        return render_template("homefake.html")
    return render_template("home.html")


@app.route("/robots.txt")
def robots():
    xml ='''User-agent: *

Disallow: /twooter
'''
    return Response(xml, mimetype='text/plain')

@app.route("/twooter")
def notflag():
    return render_template("notflag.html")


def aws_check_get(res):
    print("fetching", res)
    bad_list = ["169.254.169.254"]
    hostname = get_hostname(res)
    print("hostname", hostname)
    if socket.gethostbyname(hostname) in bad_list:
        flash("stop trying to be evil. that's not in scope")

    # manually handle redirects for aws the bad_list
    url = res
    print("now fetching", url)
    fake_headers = dict(request.headers)
    bad_headers = ['Host', 'Content-Length', 'Cache-Control', 'Origin', 'Content-Type', 'Accept', 'Connection']
    for h in bad_headers:
        if h in fake_headers:
            del fake_headers[h]
    print(fake_headers)
    while True:
        # Like every good proxy we forward ALL the user headers
        r = requests.get(url, allow_redirects=False, headers=fake_headers)
        print("r returned")
        if not r.is_redirect:
            break

        url = r.headers['Location']
        print("next vising {}".format(url))
        if get_hostname(url) in bad_list:
            flash("stop trying to be evil. that's not in scope")
            return redirect(url_for("app.home"))

    print("finished ", r)
    return r


@app.route("/profile", methods=["GET", "POST"])
def profile():
    cur_user = None

    picture_data = ''
    if not cur_user:
        if not session.get("user"):
            flash("Please log in")
            return redirect(url_for("app.login"))
        cur_user = User.query.filter_by(username=session['user']).first()

    if request.method == "POST":
        # fetch profilepicture data
        try:
            url = request.form.get("profile_picture_url", "https://ih1.redbubble.net/image.161325777.9441/flat,800x800,075,t.u1.jpg")
            # Make it easier lol
            #imagetypes = ['jpg', 'png', 'svg', 'gif', 'bmp']
            #for ft in imagetypes:
            #    if url.endswith(ft):
            #        break
            #else:
            #    flash("Not a recognised image filetype")
            #    return render_template("profile.html", user=cur_user)


            r = aws_check_get(url)
            print(r)

            profile_picture_data = base64.b64encode(r.content)
            cur_user.profile_picture_data = profile_picture_data
            db.session.add(cur_user)
            db.session.commit()
            flash("Profile updated")
        except Exception as e:
            flash(e)
    return render_template("profile.html", user = cur_user)

@app.route("/logout")
def logout():
    session['user'] = None
    session.clear()
    return redirect(url_for("app.login"))

@app.route('/login', methods=['GET', 'POST'])
def login():
    if session.get("user"):
        flash("you are already logged in")
        return(redirect(url_for("app.profile")))


    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")


        if not username or not password:
            flash("Please have enter both a username and password")
            return render_template("register.html")

        cur_user = User.query.filter_by(username = username, password = password).first()
        if not cur_user:
            flash("Invalid username and password")
            return render_template("login.html")

        session['user'] = cur_user.username
        flash("Login successful")
        return redirect(url_for("app.profile"))

    return render_template("login.html")

@app.route('/register', methods=['GET', 'POST'])
def register():
    if session.get("user"):
        flash("you are already logged in")
        return(redirect(url_for("app.profile")))

    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")

        if not username or not password:
            flash("Please have both a username and password")
            return render_template("register.html")

        # check existence of username
        check_user = User.query.filter_by(username = username).all()
        if check_user:
            flash("Username already registered")
            return render_template("register.html")

        new_user = User(username=username, password=password, profile_picture_data=b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAAAAACPAi4CAAACD0lEQVRYw+2WIbKsMBBFr0VGx+Px+GyAJaBZADtgAbiRSBxuBGIMCotCIrExEblPEHgwE+rx61c98T/tptI509253Q34l4YbcANuwL8L0K25dLOb/ADbIxquAFSQW28ETyCcLwBioPQCTA0UP9+3s4LQ/iImiC9EYAeg9QMKRFeKoAVqP0BBXXoGoCNBmulgY7FU5zPpo18XQhoS5AvvFumTsr9ZRT8gmXgFICsnpLltcwBR0bRVKoBY+3Pu22cIiLRqmyIGUH8rsQsgKkuSnBIgOdGyTbbobC0QvFaADiH6TUepv4YkH0C6sXuBUDtAuZRjJUSQ3iS0PFTXCRakjRDZnWOzpvdmDdDsE1qugZyd9k2e9CRpAmQ+QIZAk2Sf5GYRLGYSZO/+sYGLJPIrUW3HSyTNqsQX8HR9HLsHj/06WI83/9cawYMk7SMbSdLKswikJckxe1j3KD0JUgPJ3nEAch8gB4Zj18PNgxjBuDtIXYieUZXufo4BYqeDx0G+DRB6pWjC/TvqeMkci3Sg1jFYBycyIGsgWI9mBURm7YVBALKcjNVdAiCzJ72QAUhe2pqplIAYvsd6JwAEUgpgr/ePJFIAEFIGAES33wujWrtclPZ8jtpSrH5qPG4m26ahEFIVP6yEuVBSiDBt7edqs1pfWmpGa/sL2/lZvdnzDwEfIzj+7Qjuj6wbcAP+P8AXpzZqUKBcnewAAAAASUVORK5CYII=')
        db.session.add(new_user)
        db.session.commit()

        flash("New user registered")
        return redirect(url_for("app.login"))

    return render_template("register.html")

challenges/web/web3-cs6443/ssrf/app/flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>definitely OOB sql injection</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <style>
        hr { border-color: #cccccc; margin: 0; }
        .no-margins { margin: 0px; }
        .with-margins { margin: 10px; }
        .col-centered { float: none; margin: 0 auto; }
    </style>

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{{url_for("static", filename="styles.css")}}" rel="stylesheet">
  </head>

  <body>
    <div class="container mb-5">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="{{url_for("app.profile")}}">profile</a>
          </div>
          <div class="col-4 text-center">
           <a class="blog-header-logo text-dark" href="{{url_for("app.home")}}">definitely OOB sqlinjection challenge</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="btn btn-sm btn-outline-secondary mr-3" href="{{url_for("app.logout")}}">Logout</a>
            <a class="btn btn-sm btn-outline-secondary mr-3" href="{{url_for("app.login")}}">Login</a>
            <a class="btn btn-sm btn-outline-secondary" href="{{url_for("app.register")}}">Sign up</a>
          </div>
        </div>
      </header>
    </div>

    <div id="main-div" class="container mb-3">
    {# One-time system messages called Flash messages #}
    {% block flash_messages %}
        {%- with messages = get_flashed_messages(with_categories=true) -%}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category=='error' %}
                        {% set category='danger' %}
                    {% elif category == "message" %}
                        {% set category="primary" %}
                    {% endif %}
                    <div class="alert alert-{{category}}">{{ message|safe }}</div>
                {% endfor %}
            {% endif %}
        {%- endwith %}
    {% endblock %}
    </div>

    <main role="main" class="container mb-5">
    {% block main %}{% block content %}{% endblock %}{% endblock %}
    </main><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <!-- would i really go out of my way to troll you? -->
  </body>
</html>

challenges/web/web3-cs6443/ssrf/app/flaskr/templates/login.html
{% extends "base.html" %}

{% block content %}

<h1>Login</h1>
  <form action="" method=post>
    <fieldset class="form-group">
      <label>Username</label>
      <input class="form-control" name="username" placeholder="memelord420"/>
      <label>Password</label>
      <input class="form-control" name="password" type="password" placeholder="hunter2"/>
    </fieldset>
    <input type="submit" class="btn btn-primary" value="login"/>
  </form>

{% endblock %}

challenges/web/web3-cs6443/ssrf/app/flaskr/templates/profile.html
{% extends "base.html" %}

{% block content %}

<h1>Profile:</h1>
<p>Username: {{user.username}}</p>
<p>Profile Picture: </p>
<img src="data:image/jpeg;base64,{{user.profile_picture_data.decode('utf-8')}}" class="img-thumbnail">

<form method="post" action="">
  <div class="form-group" class="mt-5">
    <label>Upload new profile picture</label>
    <input class="form-control" name="profile_picture_url" type="text" placeholder="https://i.redd.it/325smhk7fyxz.jpg" /></input>
    <input class="btn btn-success mt-3" type="submit" value="Submit" />
    <!-- we forward your headers too so they don't know we're stealing their content -->
  </div>
</form>
<form>
{% endblock %}

challenges/web/web3-cs6443/ssrf/app/flaskr/templates/register.html
{% extends "base.html" %}

{% block content %}

<h1>Register</h1>
  <form action="" method=post>
    <fieldset class="form-group">
      <label>Username</label>
      <input class="form-control" name="username" placeholder="memelord420"/>
      <label>Password</label>
      <input class="form-control" name="password" type="password" placeholder="hunter2"/>
    </fieldset>
    <input type="submit" class="btn btn-primary" value="login"/>
  </form>

{% endblock %}